/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process_sa.GUI;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import process_sa.controller.Controlador;
import process_sa.controller.Md5hash;
import process_sa.models.Persona;
import process_sa.models.Usuario;

/**
 *
 * @author cvale
 */
public class CRUD_Usuario extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form CRUD_Usuario
     */
    public CRUD_Usuario() {
        initComponents();
        
        setTitle("Process SA - CRUD Usuario");
        setResizable(false);
        
        String[] titulos = {"id","rut","nombre","apellidos"};
        model = new DefaultTableModel(null, titulos){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tblPersonas.setModel(model);
        llenarComboBoxRol();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtIdPersona = new javax.swing.JTextField();
        cboxRol = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnLimpiar = new javax.swing.JButton();
        showPassword = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        menuInicio = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        crudUsuario = new javax.swing.JMenuItem();
        rolMenu = new javax.swing.JMenu();
        crudRol = new javax.swing.JMenuItem();
        personaMenu = new javax.swing.JMenu();
        crudPersona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdPersona.setEditable(false);
        txtIdPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPersonaActionPerformed(evt);
            }
        });
        txtIdPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdPersonaKeyTyped(evt);
            }
        });

        cboxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------------------" }));
        cboxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRolActionPerformed(evt);
            }
        });

        lblPassword.setText("Contraseña: ");

        lblUsuario.setText("Usuario: ");

        lblId.setText("ID: ");

        lblRol.setText("Rol: ");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");

        btnEliminar.setText("Eliminar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        showPassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\cvale\\OneDrive\\Documentos\\ProcessSA assets\\images\\botones\\passwordShow\\show0.png")); // NOI18N
        showPassword.setPreferredSize(new java.awt.Dimension(53, 27));
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Persona:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRol)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblId)
                                    .addComponent(lblPassword))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtPassword)
                                    .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPassword)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRol)
                    .addComponent(cboxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 250));

        jLabel5.setText("CRUD Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonas);

        jLabel1.setText("Persona");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 330, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 300));

        mainMenu.setText("Menú");

        menuInicio.setText("Inicio");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        mainMenu.add(menuInicio);

        logout.setText("Finalizar sesión");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        mainMenu.add(logout);

        jMenuBar1.add(mainMenu);

        usuarioMenu.setText("Usuario");

        crudUsuario.setText("CRUD Usuario");
        crudUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudUsuarioActionPerformed(evt);
            }
        });
        usuarioMenu.add(crudUsuario);

        jMenuBar1.add(usuarioMenu);

        rolMenu.setText("Rol");

        crudRol.setText("CRUD Rol");
        crudRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudRolActionPerformed(evt);
            }
        });
        rolMenu.add(crudRol);

        jMenuBar1.add(rolMenu);

        personaMenu.setText("Persona");

        crudPersona.setText("CRUD Persona");
        crudPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudPersonaActionPerformed(evt);
            }
        });
        personaMenu.add(crudPersona);

        jMenuBar1.add(personaMenu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu mn = new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_menuInicioActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        Controlador conn = new Controlador();
        
        try {
            Usuario user = recuperarDatosGUI();
            if (user.getNombre_usuario().length() == 0 || user.getContraseña().length() == 0 || user.getId_rol() == 0 || user.getId_persona() == 0 || cboxRol.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos requeridos");
            }
            else if (user.getNombre_usuario().length() >= 5){
                Md5hash md = new Md5hash();
                byte[] md5InBytes = md.digest(user.getContraseña().getBytes(md.getUTF_8()));
                System.out.println("MD5 in bytes: "+md5InBytes);
                String cipheredPassword = md.bytesToHex(md5InBytes);
                
                System.out.println("Bytes to hex: "+cipheredPassword);

                String sentencia = String.format("call PD_INSERT_USUARIO('%s', '%s', %s, %s)", user.getNombre_usuario(), cipheredPassword, user.getId_rol(), user.getId_persona());
                System.out.println("Sentencia: "+sentencia);
                conn.ejecutarProcedimientoAlmacenado(sentencia);
                JOptionPane.showMessageDialog(this, "Usuario creado correctamente!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Nombre de usuario debe tener al menos 5 caracteres...");
            }
        } 
        catch (Exception e) {
            System.out.println("Error: "+e);
        }
        finally{
            conn.desconectar();
            limpiarCampos();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void crudUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CRUD_Usuario cu = new CRUD_Usuario();
        cu.setVisible(true);
    }//GEN-LAST:event_crudUsuarioActionPerformed

    private void crudRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudRolActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CRUD_Rol cr = new CRUD_Rol();
        cr.setVisible(true);
    }//GEN-LAST:event_crudRolActionPerformed

    private void crudPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudPersonaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CRUD_Persona cp = new CRUD_Persona();
        cp.setVisible(true);
    }//GEN-LAST:event_crudPersonaActionPerformed

    private void txtIdPersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPersonaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if((txtIdPersona.getText().length() >= 4)){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdPersonaKeyTyped

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if (!showPassword.isSelected()){
            txtPassword.setEchoChar('*');
        }
        if (showPassword.isSelected()){
            txtPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if((txtId.getText().length() >= 4)){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtIdPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPersonaActionPerformed

    private void tblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonasMouseClicked
        // TODO add your handling code here:
        JTable dt = (JTable)evt.getSource();
        int row  = dt.getSelectedRow();
        
        String valor = dt.getValueAt(row, 0).toString();
        
        txtIdPersona.setText(valor);
    }//GEN-LAST:event_tblPersonasMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
        JOptionPane.showMessageDialog(this, "Has cerrado sesión");
    }//GEN-LAST:event_logoutActionPerformed

    private void cboxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRolActionPerformed
    
    public void llenarComboBoxRol(){
        Controlador conn = new Controlador();
        try {
            final List<String> listaRol = conn.getRoles();
            if (listaRol != null){
                for (String listaRoles : listaRol) {
                    System.out.println(listaRoles);
                    cboxRol.addItem(listaRoles);
                }
            }
        } catch (Exception e) {
            System.out.println("Error conexion: "+e);
        }
        conn.desconectar();
    }
    
    public void mostrarDatos(){
        Controlador conn = new Controlador();
        
        try {
            final List<Persona> listaPersona = conn.getPersonas();
            if (listaPersona != null){
                for (Persona listaPersonas : listaPersona) {
                    Object[] o = new Object[5];
                    o[0] = listaPersonas.getId();
                    o[1] = listaPersonas.getRut();
                    o[2] = listaPersonas.getNombre();
                    o[3] = listaPersonas.getApellido_paterno();
                    o[4] = listaPersonas.getApellido_materno();
                    model.addRow(o);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        conn.desconectar();
    }
    
    public Usuario recuperarDatosGUI(){
        Usuario user = new Usuario();
        
        if (txtId.getText().length() > 0){
            user.setId(Integer.parseInt(txtId.getText()));
        }
        else{
            user.setId(0);
        }
        user.setNombre_usuario(txtUsuario.getText());
        user.setContraseña(new String(txtPassword.getPassword()));
        if (cboxRol.getSelectedIndex() > 0){
            user.setId_rol(Integer.parseInt(String.valueOf(cboxRol.getSelectedItem().toString().charAt(0))));
        }
        else{
            user.setId_rol(0);
        }
        if(txtIdPersona.getText().length() > 0){
            user.setId_persona(Integer.parseInt(txtIdPersona.getText()));
        }
        else{
            user.setId_persona(0);
        }
        
        return user;
    }
    
    public void limpiarCampos(){
        txtIdPersona.setText(null);
        txtUsuario.setText(null);
        txtPassword.setText(null);
        cboxRol.setSelectedIndex(0);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Object> cboxRol;
    private javax.swing.JMenuItem crudPersona;
    private javax.swing.JMenuItem crudRol;
    private javax.swing.JMenuItem crudUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuItem menuInicio;
    private javax.swing.JMenu personaMenu;
    private javax.swing.JMenu rolMenu;
    private javax.swing.JToggleButton showPassword;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPersona;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JMenu usuarioMenu;
    // End of variables declaration//GEN-END:variables
}
