/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process_sa.GUI;

import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Random;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import process_sa.controller.Controlador;
import process_sa.models.Persona;

/**
 *
 * @author cvale
 */
public class CRUD_Persona extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_Usuario
     */
    public CRUD_Persona() {
        initComponents();
        
        setTitle("Process SA - CRUD Persona");
        setResizable(false);
        
        llenarComboBoxRegion();
        llenarComboBoxCiudad();
        llenarComboBoxComuna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboxDigito = new javax.swing.JComboBox<>();
        txtAppaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApmaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboxComuna = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDireccionNumero = new javax.swing.JTextField();
        cboxRegion = new javax.swing.JComboBox<>();
        cboxCiudad = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        menuInicio = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        crudUsuario = new javax.swing.JMenuItem();
        rolMenu = new javax.swing.JMenu();
        crudRol = new javax.swing.JMenuItem();
        personaMenu = new javax.swing.JMenu();
        crudPersona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        txtId.setMinimumSize(new java.awt.Dimension(7, 25));
        txtId.setPreferredSize(new java.awt.Dimension(7, 27));
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel2.add(txtId);
        txtId.setBounds(110, 20, 45, 27);

        lblPassword.setText("Nombre:");
        jPanel2.add(lblPassword);
        lblPassword.setBounds(51, 86, 60, 14);

        lblUsuario.setText("RUT: ");
        jPanel2.add(lblUsuario);
        lblUsuario.setBounds(72, 55, 40, 14);

        lblId.setText("ID: ");
        jPanel2.add(lblId);
        lblId.setBounds(86, 24, 30, 14);

        txtRut.setPreferredSize(new java.awt.Dimension(7, 27));
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });
        jPanel2.add(txtRut);
        txtRut.setBounds(110, 50, 150, 27);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrear);
        btnCrear.setBounds(10, 360, 79, 23);

        btnEditar.setText("Editar");
        jPanel2.add(btnEditar);
        btnEditar.setBounds(110, 360, 79, 23);

        btnEliminar.setText("Eliminar");
        jPanel2.add(btnEliminar);
        btnEliminar.setBounds(200, 360, 79, 23);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar);
        btnLimpiar.setBounds(300, 360, 77, 23);

        jLabel1.setText("Apellido paterno:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 117, 100, 14);

        jLabel2.setText("Región:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 240, 70, 14);

        txtNombre.setPreferredSize(new java.awt.Dimension(7, 27));
        jPanel2.add(txtNombre);
        txtNombre.setBounds(110, 80, 228, 27);

        jLabel3.setText("-");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 50, 10, 20);

        cboxDigito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "K" }));
        cboxDigito.setPreferredSize(new java.awt.Dimension(32, 18));
        jPanel2.add(cboxDigito);
        cboxDigito.setBounds(280, 50, 50, 30);

        txtAppaterno.setPreferredSize(new java.awt.Dimension(7, 27));
        jPanel2.add(txtAppaterno);
        txtAppaterno.setBounds(110, 110, 228, 27);

        jLabel4.setText("Apellido materno:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 145, 96, 14);

        txtApmaterno.setPreferredSize(new java.awt.Dimension(7, 27));
        jPanel2.add(txtApmaterno);
        txtApmaterno.setBounds(110, 140, 228, 27);

        jLabel6.setText("Dirección:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 210, 70, 14);

        cboxComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------------------" }));
        cboxComuna.setPreferredSize(new java.awt.Dimension(57, 18));
        jPanel2.add(cboxComuna);
        cboxComuna.setBounds(110, 290, 220, 30);

        jLabel7.setText("Ciudad:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 270, 70, 14);

        jLabel8.setText("Comuna:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 300, 70, 14);

        txtDireccionNumero.setPreferredSize(new java.awt.Dimension(7, 27));
        txtDireccionNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionNumeroKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccionNumero);
        txtDireccionNumero.setBounds(260, 200, 78, 27);

        cboxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------------------" }));
        cboxRegion.setPreferredSize(new java.awt.Dimension(57, 18));
        jPanel2.add(cboxRegion);
        cboxRegion.setBounds(110, 230, 220, 30);

        cboxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------------------" }));
        cboxCiudad.setPreferredSize(new java.awt.Dimension(57, 18));
        jPanel2.add(cboxCiudad);
        cboxCiudad.setBounds(110, 260, 220, 30);

        txtDireccion.setPreferredSize(new java.awt.Dimension(7, 27));
        jPanel2.add(txtDireccion);
        txtDireccion.setBounds(110, 200, 140, 27);

        txtEmail.setPreferredSize(new java.awt.Dimension(7, 27));
        jPanel2.add(txtEmail);
        txtEmail.setBounds(110, 170, 228, 27);

        jLabel9.setText("Email:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 180, 50, 14);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 420));

        jLabel5.setText("CRUD Persona");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 460));

        mainMenu.setText("Menú");

        menuInicio.setText("Inicio");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        mainMenu.add(menuInicio);

        logout.setText("Finalizar sesión");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        mainMenu.add(logout);

        jMenuBar1.add(mainMenu);

        usuarioMenu.setText("Usuario");

        crudUsuario.setText("CRUD Usuario");
        crudUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudUsuarioActionPerformed(evt);
            }
        });
        usuarioMenu.add(crudUsuario);

        jMenuBar1.add(usuarioMenu);

        rolMenu.setText("Rol");

        crudRol.setText("CRUD Rol");
        crudRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudRolActionPerformed(evt);
            }
        });
        rolMenu.add(crudRol);

        jMenuBar1.add(rolMenu);

        personaMenu.setText("Persona");

        crudPersona.setText("CRUD Persona");
        crudPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudPersonaActionPerformed(evt);
            }
        });
        personaMenu.add(crudPersona);

        jMenuBar1.add(personaMenu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu mn = new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_menuInicioActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        Controlador conn = new Controlador();
        
        Persona persona = recuperarDatosGUI();
        
        try {
            if (persona.getRut().length() == 0 || persona.getNombre().length() == 0 || persona.getApellido_paterno().length() == 0 || persona.getApellido_materno().length() == 0
                    || persona.getId_region() == 0 || persona.getId_direccion() == 0 || persona.getId_ciudad() == 0 || persona.getId_comuna() == 0 || persona.getEmail().length() == 0){
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos requeridos");
            }
            else{
                if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", persona.getEmail()))){
                    JOptionPane.showMessageDialog(this, "Por favor, ingresa un email válido", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    String sentencia = String.format("call PD_INSERT_PERSONA('%s', '%s', '%s', '%s', '%s', %s)", persona.getRut(), persona.getNombre(), persona.getApellido_paterno(), persona.getApellido_materno(), persona.getEmail(), persona.getId_direccion());
                    System.out.println("Sentencia: "+sentencia);
                    conn.ejecutarProcedimientoAlmacenado(sentencia);
                    JOptionPane.showMessageDialog(this, "Persona creada correctamente!");
                }
            }
        } 
        catch (Exception e) {
            System.out.println("Error: "+e);
        }
        finally{
            conn.desconectar();
            limpiarCampos();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void crudUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CRUD_Usuario cu = new CRUD_Usuario();
        cu.setVisible(true);
    }//GEN-LAST:event_crudUsuarioActionPerformed

    private void crudRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudRolActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CRUD_Rol cr = new CRUD_Rol();
        cr.setVisible(true);
    }//GEN-LAST:event_crudRolActionPerformed

    private void crudPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudPersonaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CRUD_Persona cp = new CRUD_Persona();
        cp.setVisible(true);
    }//GEN-LAST:event_crudPersonaActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if((txtRut.getText().length() >= 8)){
            evt.consume();
        }
    }//GEN-LAST:event_txtRutKeyTyped

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if((txtId.getText().length() >= 4)){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtDireccionNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionNumeroKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
        if((txtDireccionNumero.getText().length() >= 6)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDireccionNumeroKeyTyped

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
        JOptionPane.showMessageDialog(this, "Has cerrado sesión");
    }//GEN-LAST:event_logoutActionPerformed
   
    public void llenarComboBoxRegion(){
        Controlador conn = new Controlador();
        try {
            List<String> listaRegion = conn.getRegiones();
            if (listaRegion.size() > 0){
                for (String listaRegiones : listaRegion) {
                    cboxRegion.addItem(listaRegiones);
                }
            }
        } catch (Exception e) {
            System.out.println("Error region: "+e);
        }
        conn.desconectar();
    }
    
    public void llenarComboBoxCiudad(){
        Controlador conn = new Controlador();
        try {
            final List<String> listaRegion = conn.getCiudad();
            if (listaRegion != null){
                for (String listaRegiones : listaRegion) {
                    cboxCiudad.addItem(listaRegiones);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        conn.desconectar();
    }
    
    public void llenarComboBoxComuna(){
        Controlador conn = new Controlador();
        try {
            final List<String> listaRegion = conn.getComuna();
            if (listaRegion != null){
                for (String listaRegiones : listaRegion) {
                    cboxComuna.addItem(listaRegiones);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        conn.desconectar();
    }
    
    public Persona recuperarDatosGUI(){
        Persona persona = new Persona();
        
        if (txtId.getText().length() > 0){
            persona.setId(Integer.parseInt(txtId.getText()));
        }
        else{
            persona.setId(0);
        }
        persona.setRut(txtRut.getText()+"-"+cboxDigito.getSelectedItem());
        persona.setNombre(txtNombre.getText());   
        persona.setApellido_paterno(txtAppaterno.getText());
        persona.setApellido_materno(txtApmaterno.getText());
        persona.setEmail(txtEmail.getText());
        if (cboxComuna.getSelectedIndex() > 0){
            persona.setId_direccion(getDireccionId(txtDireccion.getText(), txtDireccionNumero.getText(), Integer.parseInt(String.valueOf(cboxComuna.getSelectedItem().toString().charAt(0)))));
            persona.setId_comuna(Integer.parseInt(String.valueOf(cboxComuna.getSelectedItem().toString().charAt(0))));
        }else{
            persona.setId_direccion(0);
            persona.setId_comuna(0);
        }
        if (cboxRegion.getSelectedIndex() > 0){
            persona.setId_region(Integer.parseInt(String.valueOf(cboxRegion.getSelectedItem().toString().charAt(0))));
        }else{
            persona.setId_region(0);
        }
        
        if (cboxCiudad.getSelectedIndex() > 0){
            persona.setId_ciudad(Integer.parseInt(String.valueOf(cboxCiudad.getSelectedItem().toString().charAt(0))));
        }else{
            persona.setId_ciudad(0);
        }
        
        return persona;
    }
    
    public int getDireccionId(String calle, String numero, int id_comuna){
        Controlador conn = new Controlador();
        
        String sentencia = String.format("call PD_INSERT_DIRECCION('%s', '%s', %s)", calle, numero, id_comuna);
        //System.out.println("Sentencia: "+sentencia);
        conn.ejecutarProcedimientoAlmacenado(sentencia);
        //JOptionPane.showMessageDialog(this, "Dirección añadida correctamente!");
        int last_id = conn.getIdDireccion();
        
        return last_id;
    }
    
    public void limpiarCampos(){
        txtId.setText(null);
        txtRut.setText(null);
        cboxDigito.setSelectedIndex(0);
        txtNombre.setText(null);
        txtAppaterno.setText(null);
        txtApmaterno.setText(null);
        txtEmail.setText(null);
        txtDireccion.setText(null);
        txtDireccionNumero.setText(null);
        cboxRegion.setSelectedIndex(0);
        cboxCiudad.setSelectedIndex(0);
        cboxComuna.setSelectedIndex(0);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboxCiudad;
    private javax.swing.JComboBox<String> cboxComuna;
    private javax.swing.JComboBox<String> cboxDigito;
    private javax.swing.JComboBox<String> cboxRegion;
    private javax.swing.JMenuItem crudPersona;
    private javax.swing.JMenuItem crudRol;
    private javax.swing.JMenuItem crudUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuItem menuInicio;
    private javax.swing.JMenu personaMenu;
    private javax.swing.JMenu rolMenu;
    private javax.swing.JTextField txtApmaterno;
    private javax.swing.JTextField txtAppaterno;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionNumero;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JMenu usuarioMenu;
    // End of variables declaration//GEN-END:variables
}
